version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "53308:3306"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [51027:1025, 51082:1080]
###< symfony/mailer ###
