version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:10.9.1-rc'
    container_name: db-sorties
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: app-sorties
      MYSQL_ROOT_PASSWORD:
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
