<?php

namespace App\Controller\Admin;

use App\Entity\Lieu;
use App\Form\LieuType;
use App\Repository\LieuRepository;
use App\Repository\VilleRepository;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\KeyValueStore;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Dto\EntityDto;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\FormField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\Form\FormInterface;

class LieuCrudController extends AbstractCrudController
{
    private VilleRepository $villeRepository;
    private LieuRepository $lieuRepository;

    public function __construct(VilleRepository $villeRepository,
                                LieuRepository $lieuRepository,
    )
    {
        $this->villeRepository = $villeRepository;
        $this->lieuRepository = $lieuRepository;
    }

    public static function getEntityFqcn(): string
    {
        return Lieu::class;
    }
    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInSingular('Villes')
            ->setFormOptions($lieu->getVille())
            ;
    }

    public function configureFields(string $pageName): iterable
    {
        $lieus = $this->lieuRepository->findAll();
        foreach ($lieus as $lieu){
            $codePostal = $lieu->getVille();

            $field = TextField::new($lieu->getVille()->getCodePostal());

        return [
            FormField::addPanel( 'Lieux' )->setIcon( 'fa fa-map-marker'),
            TextField::new('nom', 'Nom'),
            TextField::new('rue', 'Rue'),
            NumberField::new('latitude', 'Latitude'),
            NumberField::new('longitude', 'Longitude'),
            AssociationField::new('ville', 'Villes'),
//            $field
        ];
        }
    }

    public function new(AdminContext $context)
    {
        return parent::new($context); // TODO: Change the autogenerated stub
    }

    public function createForm(string $type, mixed $data = null, array $options = []): FormInterface
    {
        $villes = $this->villeRepository->findAll();
        $lieu = new Lieu();

        return parent::createForm($type, $data, $options);
        // TODO: Change the autogenerated stub
    }


    public function configureActions(Actions $actions): Actions{
        return $actions
            ->add(Crud::PAGE_INDEX, Action::DETAIL)
            ->update(Crud::PAGE_INDEX,Action::NEW,function(Action $action){
                return $action->setIcon('fas fa-newspaper pe-1')->setLabel('Ajouter un article');
            })
            ->update(Crud::PAGE_INDEX,Action::EDIT,function(Action $action){
                return $action->setIcon('fas fa-edit text-warning')->setLabel('Editer')->addCssClass('text-dark');
            })
            ->update(Crud::PAGE_INDEX,Action::DELETE,function(Action $action){
                return $action->setIcon('fas fa-trash text-danger')->setLabel('Supprimer')->addCssClass('text-dark');
            })
            ->update(Crud::PAGE_INDEX,Action::DETAIL,function(Action $action){
                return $action->setIcon('fas fa-eye text-info')->setLabel('Consulter')->addCssClass('text-dark');
            });
    }

}
